### ISSUE TITLE
First install

### ISSUE THREAD

**Issue by solune** [DSI-Universite-Rennes2/isou#1]
Bonjour,
Lors d'une nouvelle installation, comment accéder à la page de configuration ?
// Définis si l'application est en mode developpement (désactive la phase d'authentification).
define('DEV', true);
Pourtant impossible de passer l'authentification.

**Comment by jboulen** [comment]
Bonjour,

Effectivement, la constante DEV n'était plus prise en compte. C'est maintenant corrigé.

J'ai également mis à jour le README.md afin de préciser les identifiants par défaut de l'utilisateur créé lors de l'installation.

Merci de nous avoir signalé ce problème.

Cordialement,
