### ISSUE TITLE
cron mktime

### ISSUE THREAD

**Issue by solune** [DSI-Universite-Rennes2/isou#18]
Bonjour,
Lors de l'exécution du cron j'ai cette erreur:
```[16-Jun-2023 14:10:19 Europe/Paris] PHP Fatal error:  Uncaught TypeError: mktime() expects parameter 1 to be int, string given in /app/isou/libs/cron.php:400
Stack trace:
#0 /app/isou/libs/cron.php(400): mktime('06', '00')
#1 /app/isou/cron.php(123): cron_report()
#2 {main}
  thrown in /app/isou/libs/cron.php on line 400

Fatal error: Uncaught TypeError: mktime() expects parameter 1 to be int, string given in /app/isou/libs/cron.php:400
Stack trace:
#0 /app/isou/libs/cron.php(400): mktime('06', '00')
#1 /app/isou/cron.php(123): cron_report()
#2 {main}
  thrown in /app/isou/libs/cron.php on line 400
```

Faut il changer le type du champ dans la base ou changer le code ?
Bonne journée

**Comment by jboulen** [comment]
Bonjour,

Merci pour ce retour.

En regardant le code, je m'aperçois que j'ai oublié de réimplémenter la fonctionnalité de rapport.

Pour contourner ce problème, vous pouvez au choix : 
- désactiver le rapport quotidien
- forcer le typage en ajoutant `(int)` devant les paramètres de la fonction ; `$daily_cron_time = mktime((int) $daily_cron_time[0], (int) $daily_cron_time[1]);`

Je pense que désactiver le rapport quotidien dans l'interface web est le plus simple. De toute façon, en l'état, aucun rapport ne sera envoyé.

J'essayerai de réimplémenter cette fonctionnalité dès que possible.

Bonne fin de semaine,

**Comment by jboulen** [comment]
Bonjour,

La fonctionnalité d'envoi des rapports quotidiens a été réimplémentée.

Merci d'avoir pris le temps d'ouvrir une issue !
