### ISSUE TITLE
installer la dernière version du paquet minishlink/web-push

### ISSUE THREAD

**Issue by Isma399** [DSI-Universite-Rennes2/isou#2]
Bonjour,

lors d'une installation sur Centos7 avec Composer version 1.9.2, je rencontre cette erreur:

> Package spomky-labs/jose is abandoned, you should avoid using it. Use web-token/jwt-framework instead.

Est-ce que c'est bloquant pour le fonctionnement de l'application?
Merci,

**Comment by jboulen** [comment]
Bonjour,

Ce message d'avertissement n'est pas bloquant pour le bon fonctionnement de l'application.

Cette dépendance est utilisée par la bibliothèque qui nous permet de générer des notifications web.

Par contre, il semblerait que nous n'utilisions pas la dernière version de cette bibliothèque. Je me permets donc de renommer votre issue afin de traiter ce problème dès que possible.

Merci de nous avoir signalé cette erreur,
