### ISSUE TITLE
Service nagios supprimé

### ISSUE THREAD

**Issue by solune** [DSI-Universite-Rennes2/isou#3]
Bonjour,
Est il normal de ne plus avoir l'alerte du style "Service nagios supprimé" lorsqu'un check a été supprimé dans nagios ?
(Merci pour votre travail)
Marc Boisis - La Rochelle Université

**Comment by jboulen** [comment]
Bonjour,

Non, ce n'est pas normal. Je pense qu'il s'agit d'une régression.

On parle bien d'une information dans la rubrique d'administration Services > Services Nagios ?

**Comment by solune** [comment]
oui c'est bien cela.
J'ai des messages du type : "Service non rattaché à un service Isou" mais rien concernant les services qui ne sont plus dans nagios.

**Comment by jboulen** [comment]
C'est corrigé.

Merci de nous avoir signalé cet oubli.

Bonne journée,
